#!/bin/bash
# claude-cron task runner — thin wrapper around claude -p
# All config (max-turns, timeout, budget) comes from crontab args,
# generated by the /deploy skill.
#
# Usage: run-task.sh <task-name> --max-turns N --timeout S [--max-budget USD] [--model MODEL]

set -euo pipefail

TASK_NAME="$1"; shift

CLAUDE_CRON_DIR="$HOME/claude-cron"
DATA_DIR="$CLAUDE_CRON_DIR/data"
TASK_FILE="$CLAUDE_CRON_DIR/tasks/${TASK_NAME}.md"

# Parse args
MAX_TURNS=50; TIMEOUT=3600; MAX_BUDGET=""; MODEL=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --max-turns)  MAX_TURNS="$2";  shift 2 ;;
        --timeout)    TIMEOUT="$2";    shift 2 ;;
        --max-budget) MAX_BUDGET="$2"; shift 2 ;;
        --model)      MODEL="$2";     shift 2 ;;
        *) shift ;;
    esac
done

# Logging
LOG_DIR="$DATA_DIR/logs/$TASK_NAME"
LOG_FILE="$LOG_DIR/${TASK_NAME}_$(date +%Y%m%d_%H%M%S).log"
mkdir -p "$LOG_DIR"

{ echo "== $TASK_NAME | $(date -Iseconds) =="; echo ""; } >> "$LOG_FILE"

# Signal to Claude that this is an unattended cron execution
export CLAUDE_CRON=1
export CLAUDE_CRON_TASK="$TASK_NAME"

# Run from repo root so Claude finds CLAUDE.md
cd "$CLAUDE_CRON_DIR"

# Build claude args
ARGS=(--print --max-turns "$MAX_TURNS" --dangerously-skip-permissions)
ARGS+=(--append-system-prompt "You are running as an unattended cron job. Execute the task immediately. Do not summarise the task, do not ask questions, do not wait for input.")
[[ -n "$MAX_BUDGET" ]] && ARGS+=(--max-budget-usd "$MAX_BUDGET")
[[ -n "$MODEL" ]] && ARGS+=(--model "$MODEL")

# Run — pass task file contents as the prompt argument
PROMPT="$(cat "$TASK_FILE")"
EXIT_CODE=0
timeout --signal=KILL "$TIMEOUT" \
    claude "${ARGS[@]}" "$PROMPT" >> "$LOG_FILE" 2>&1 || EXIT_CODE=$?

{ echo ""; echo "== exit $EXIT_CODE | $(date -Iseconds) =="; } >> "$LOG_FILE"

# Alert on failure
if [[ $EXIT_CODE -ne 0 ]]; then
    curl -sf -X POST http://169.254.169.254/gateway/email/send \
        -H "Content-Type: application/json" \
        -d "$(jq -n \
            --arg s "claude-cron: $TASK_NAME failed (exit $EXIT_CODE)" \
            --arg b "$(tail -20 "$LOG_FILE")" \
            '{subject:$s, body:$b}')" || true
fi

# Rotate logs: keep last 50
ls -1t "$LOG_DIR"/*.log 2>/dev/null | tail -n +51 | xargs -r rm
exit $EXIT_CODE
